backend:
  name: git-gateway
  branch: master

media_folder: public/cms
logo_url: https://dev.carmichaelkingham.com/svg/logo-blue.svg
display_url: https://dev.carmichaelkingham.com

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - {
              label: 'Banner Text',
              name: 'bannerText',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Banner Image Mobile',
              name: 'bannerImageMobile',
              widget: 'image',
              required: true,
            }
          - {
              label: 'Banner Image Web',
              name: 'bannerImageWeb',
              widget: 'image',
              required: true,
            }
          - {
              label: 'About Text',
              name: 'aboutText',
              widget: 'text',
              required: true,
            }
      - label: 'About Us'
        name: 'aboutUs'
        file: 'content/about.md'
        fields:
          - {
              label: 'Page Title',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - { label: 'Quote', name: 'quote', widget: 'string', required: true }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - label: 'Our People'
        name: 'ourPeople'
        file: 'content/ourPeople.md'
        fields:
          - {
              label: 'Page Title',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
      - label: 'Expertise'
        name: 'expertise'
        file: 'content/expertise.md'
        fields:
          - {
              label: 'Page Title',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Page Summary',
              name: 'pageSummary',
              widget: 'text',
              required: true,
            }
      - label: 'Pricing'
        name: 'pricing'
        file: 'content/pricing.md'
        fields:
          - {
              label: 'Page Title',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Packages Title',
              name: 'packagesTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Gold Title',
              name: 'goldTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Gold Price',
              name: 'goldPrice',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Silver Title',
              name: 'silverTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Silver Price',
              name: 'silverPrice',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Bronze Title',
              name: 'bronzeTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Bronze Price',
              name: 'bronzePrice',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Packages Pricing Text',
              name: 'pricingText',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Add Ons Title',
              name: 'addOnsTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Self Assessment Title',
              name: 'selfAssessmentTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Self Assessment Text',
              name: 'selfAssessmentText',
              widget: 'string',
              required: true,
            }
          - label: Gold
            name: gold
            widget: list
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - {
                  label: Subtext,
                  name: subtext,
                  widget: string,
                  required: false,
                }
          - label: Silver
            name: silver
            widget: list
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - {
                  label: Subtext,
                  name: subtext,
                  widget: string,
                  required: false,
                }
          - label: Bronze
            name: bronze
            widget: list
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - {
                  label: Subtext,
                  name: subtext,
                  widget: string,
                  required: false,
                }

      - label: 'Blog'
        name: 'blog'
        file: 'content/blog.md'
        fields:
          - {
              label: 'Page Title',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Page Summary',
              name: 'pageSummary',
              widget: 'text',
              required: true,
            }
      - label: 'Contact Us'
        name: 'contactUs'
        file: 'content/contactUs.md'
        fields:
          - {
              label: Page Title,
              name: pageTitle,
              widget: string,
              required: true,
            }
          - {
              label: Page Summary,
              name: pageSummary,
              widget: text,
              required: true,
            }
      - label: 'Careers'
        name: 'careers'
        file: 'content/careers.md'
        fields:
          - {
              label: Page Title,
              name: pageTitle,
              widget: string,
              required: true,
            }
          - {
              label: Page Summary,
              name: pageSummary,
              widget: text,
              required: true,
            }
      - label: 'Privacy Policy'
        name: 'privacyPolicy'
        file: 'content/privacyPolicy.md'
        fields:
          - {
              label: 'Page Title',
              name: 'pageTitle',
              widget: 'string',
              required: true,
            }
          - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - label: 'Expertise Cards'
    name: 'expertiseCards'
    folder: 'content/expertise'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - label: 'Team Members'
    name: 'teamMembers'
    folder: 'content/team'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false }
      - { label: 'Image', name: 'image', widget: 'image', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - label: 'Blog Posts'
    name: 'blog'
    folder: 'content/blogPosts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          required: true,
        }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          required: true,
        }
      - { label: 'Summary', name: 'summary', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false }

  - label: 'General'
    name: 'general'
    files:
      - label: 'Company Details'
        name: 'companyDetails'
        file: 'content/companyDetails.md'
        fields:
          - {
              label: 'Company Name',
              name: 'companyName',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Company Registration',
              name: 'companyRegistration',
              widget: 'string',
              required: true,
            }
          - {
              label: 'Phone Number',
              name: 'phone',
              widget: 'string',
              required: true,
            }
          - { label: 'Email', name: 'email', widget: 'string', required: true }
          - {
              label: 'Address',
              name: 'address',
              widget: 'string',
              required: true,
            }
      - label: 'Navigation'
        name: 'navigation'
        file: 'content/navigation.md'
        fields:
          - label: Navigation
            name: navigation
            widget: list
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - { label: Icon, name: icon, widget: image, required: true }
              - { label: href, name: href, widget: hidden }
          - label: Company
            name: company
            widget: list
            fields:
              - { label: Label, name: label, widget: string, required: true }
              - { label: href, name: href, widget: hidden }
          - label: Partners
            name: partners
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Icon, name: icon, widget: image, required: true }
              - { label: href, name: href, widget: hidden }
          - label: Connect
            name: connect
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Icon, name: icon, widget: hidden }
              - { label: href, name: href, widget: string, required: true }
