backend:
  name: git-gateway
  branch: dev
media_folder: static/img
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/home.md"
        fields:
          - {
              label: "Banner Text",
              name: "bannerText",
              widget: "string",
              required: true,
            }
          - {
              label: "About Text",
              name: "aboutText",
              widget: "markdown",
              required: true,
            }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - {
                  label: Credentials,
                  name: credentials,
                  widget: string,
                  required: true,
                }
              - { label: Photo, name: photo, widget: image, required: true }
              - { label: Link, name: link, widget: hidden }
      - label: "Expertise"
        name: "expertise"
        file: "content/expertise.md"
        fields:
          - label: Expertise
            name: expertise
            widget: list
            fields:
              - { label: Title, name: title, widget: string, required: true }
              - {
                  label: Content,
                  name: content,
                  widget: markup,
                  required: true,
                }
              - { label: Id, name: id, widget: number, required: true }
  - label: "Blog"
    name: "blog"
    folder: "content/blogPosts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: true,
        }
      - {
          label: "Summary",
          name: "summary",
          widget: "markdown",
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list" }
