backend:
  name: git-gateway
  branch: dev

media_folder: static/cms

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "content/home.md"
        fields:
          - {
              label: "Banner Text",
              name: "bannerText",
              widget: "string",
              required: true,
            }
          - {
              label: "About Text",
              name: "aboutText",
              widget: "markdown",
              required: true,
            }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string, required: true }
              - {
                  label: Credentials,
                  name: credentials,
                  widget: string,
                  required: true,
                }
              - { label: Photo, name: photo, widget: image, required: true }
              - { label: Link, name: link, widget: hidden }
      - label: "About Us"
        name: "aboutUs"
        file: "content/about.md"
        fields:
          - {
              label: "Page Title",
              name: "pageTitle",
              widget: "string",
              required: true,
            }
          - { label: "Quote", name: "quote", widget: "string", required: true }
          - { label: "Body", name: "body", widget: "markdown", required: true }
      - label: "Expertise"
        name: "expertise"
        file: "content/expertise.md"
        fields:
          - label: Expertise
            name: expertise
            widget: list
            fields:
              - { label: Title, name: title, widget: string, required: true }
              - {
                  label: Page Summary,
                  name: pageSummary,
                  widget: string,
                  required: true,
                }
              - {
                  label: Content,
                  name: content,
                  widget: markdown,
                  required: true,
                }
              - { label: Id, name: id, widget: number, required: true }
      - label: "Our People"
        name: "ourPeople"
        file: "content/ourPeople.md"
        fields:
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: title, widget: string, required: true }
              - {
                  label: Credentials,
                  name: credentials,
                  widget: string,
                  required: true,
                }
              - { label: Bio, name: content, widget: markdown, required: true }
      - label: "Contact Us"
        name: "contactUs"
        file: "content/contactUs.md"
        fields:
          - {
              label: Page Title,
              name: pageTitle,
              widget: string,
              required: true,
            }
          - {
              label: Page Summary,
              name: pageSummary,
              widget: string,
              required: true,
            }
      - label: "Careers"
        name: "careers"
        file: "content/careers.md"
        fields:
          - {
              label: Page Title,
              name: pageTitle,
              widget: string,
              required: true,
            }
          - {
              label: Page Summary,
              name: pageSummary,
              widget: string,
              required: true,
            }
      - label: "Privacy Policy"
        name: "privacyPolicy"
        file: "content/privacyPolicy.md"
        fields:
          - {
              label: "Page Title",
              name: "pageTitle",
              widget: "string",
              required: true,
            }
          - { label: "Body", name: "body", widget: "markdown", required: true }

  - label: "Blog"
    name: "blog"
    folder: "content/blogPosts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: true,
        }
      - { label: "Summary", name: "summary", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "general"
    label: "General"
    files:
      - label: "Company Details"
        name: "companyDetails"
        file: "content/companyDetails.md"
        fields:
          - {
              label: "Company Name",
              name: "companyName",
              widget: "string",
              required: true,
            }
          - {
              label: "Company Registration",
              name: "companyRegistration",
              widget: "string",
              required: true,
            }
          - {
              label: "Phone Number",
              name: "phone",
              widget: "string",
              required: true,
            }
          - { label: "Email", name: "email", widget: "string", required: true }
          - {
              label: "Address",
              name: "address",
              widget: "string",
              required: true,
            }
