backend:
  name: git-gateway
  branch: master
  site_domain: dev.carmichaelkingham.co.uk
media_folder: static/img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Banner Text", name: "bannerText", widget: "string" }
          - { label: "About Text", name: "aboutText", widget: "string" }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Credentials, name: credentials, widget: string }
              - { label: Bio, name: bio, widget: string }
              - { label: Photo, name: photo, widget: image }
              - { label: Link, name: link, widget: hidden }
